
-- EJECUTAR TODO ESTE SCRIPT EN EL EDITOR SQL DE SUPABASE --

-- ==========================================
-- 1. TABLA PRINCIPAL DE DATOS (store_data)
-- Almacena productos, configuración, pedidos, etc. en formato JSON
-- ==========================================

DROP TABLE IF EXISTS store_data;

CREATE TABLE store_data (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  products jsonb DEFAULT '[]'::jsonb,
  categories jsonb DEFAULT '[]'::jsonb,
  settings jsonb DEFAULT '{}'::jsonb,
  zones jsonb DEFAULT '[]'::jsonb,
  banners jsonb DEFAULT '[]'::jsonb,
  coupons jsonb DEFAULT '[]'::jsonb,
  orders jsonb DEFAULT '[]'::jsonb,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Habilitar seguridad pero permitir acceso público (necesario para la Key Anónima)
ALTER TABLE store_data ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acceso Publico Total Store" 
ON store_data 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- IMPORTANTE: Inicializar la tienda con la fila ID 1
-- La app busca específicamente esta fila.
INSERT INTO store_data (id) VALUES (1);


-- ==========================================
-- 2. TABLA DE USUARIOS (app_users)
-- Gestiona clientes y administradores
-- ==========================================

DROP TABLE IF EXISTS app_users;

CREATE TABLE app_users (
  id text PRIMARY KEY,
  email text UNIQUE NOT NULL,
  password text NOT NULL, -- Nota: En producción real, usar Auth de Supabase o Hashear
  name text,
  role text DEFAULT 'user', -- 'user' o 'admin'
  avatar text,
  phone text,
  address text,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Habilitar seguridad pero permitir registro y login público
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acceso Publico Total Usuarios" 
ON app_users 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- (Opcional) Crear un usuario Admin por defecto si lo deseas
-- Descomenta las siguientes lineas si quieres un admin inicial en la BD:
-- INSERT INTO app_users (id, email, password, name, role, avatar)
-- VALUES ('admin-id', 'admin@shoespot.com', 'admin', 'Super Admin', 'admin', 'https://cdn-icons-png.flaticon.com/512/2942/2942813.png');
